### ISSUE TITLE
Redirect screen contains fields, button visible to user

### ISSUE THREAD

**Issue by LaurensBurger** [maykinmedia/django-digid-eherkenning#25]
![image](https://user-images.githubusercontent.com/112621537/214845131-7677a273-42e9-497a-aee4-b734ed5960cd.png)
only visible for a short time, but would be nice if this is hidden

**Comment by alextreme** [comment]
@SonnyBA or @Bartvaderkin , if one of you wants to investigate within the context of your current project (VIPS or OIP) feel free.

**Comment by alextreme** [comment]
Discussed with @joeribekker and attempted on OIP acc ("

Note: CSP restrictions forbid inline styling so this isn't possible within the template ( https://github.com/maykinmedia/django-digid-eherkenning/blob/master/digid_eherkenning/templates/digid_eherkenning/post_binding.html ).
This will require a separate css file in /static/ to hide the form.

**Comment by joeribekker** [comment]
Maybe for non-frontend only apps, we an make a login form/button that directly performs the post to Logius instead of the separate screen?

**Comment by sergei-maertens** [comment]
> Maybe for non-frontend only apps, we an make a login form/button that directly performs the post to Logius instead of the separate screen?

Having skimmed through the spec and SAMLv2 with POST binding, I don't think that's even allowed :grimacing:

**Comment by joeribekker** [comment]
If I look at mijn.haarlem.nl, they transition smoothly from login button to DigiD page without any intermediate screen.

**Comment by alextreme** [comment]
@joeribekker I suspect they use a different binding then, see https://en.wikipedia.org/wiki/SAML_2.0#SAML_2.0_profiles

**Comment by joeribekker** [comment]
Can confirm, the removal of this screen can be achieved with a different binding (redirect instead of post).
