### ISSUE TITLE
Make LoA a required field and set a sane default

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-digid-eherkenning#38]
Currently, if no LoA is configured in the admin/model, an invalid request is sent to (at least) eHerkenning, since there is no LoA set.

We should set a sane default, which should have been done to make things backwards compatible.

LoA DigiD: midden
LoA eHerkenning 2+

**Comment by CharString** [comment]
> We should set a sane default, which should have been done to make things backwards compatible.

This is not new behaviour. `EherhenningConfiguration.loa` hasn't been touched. The settings had a default value `loa3`, but wasn't required, so an active, accidental misconfigure was possible.

For the data migration I've used the suggested `2+`, but kept the default `3`.
Technically it's still possible to misconfigure; `choices` creates no integrity check on the database, just on the created admin forms. It's just even harder.
