### ISSUE TITLE
The entityID is incorrectly resolved for URNs

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-digid-eherkenning#58]
https://github.com/maykinmedia/django-digid-eherkenning/blob/970d3edbc512a08e2366d238b17de89d4150c35a/digid_eherkenning/models/base.py#L226

**Comment by SilviaAmAm** [comment]
This was added during this: https://github.com/maykinmedia/django-digid-eherkenning/issues/45

From the issues/discussions linked, I don't see any reason as to why the URLs were used for eHerkenning.

**Comment by SilviaAmAm** [comment]
Oups, reopened issue in wrong library
