### ISSUE TITLE
Allow multiple certificates to be added to the XML metadata

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-digid-eherkenning#74]
We should be able to add multiple certificates to the DigiD and eHerkenning config, so that they are all used in the metadata.

This way, when a certificates expires, we can upload the new certificate and generate metadata containing both the old (currently valid) and the future valid certificate. This enables a smooth transition.

**Comment by sergei-maertens** [comment]
Published django-simple-certmanager 2.2.0 for this, work in django-digid-eherkenning is ongoing.
